version: "3.5"

services:
  holepunch-node:
    container_name: holepunch-node
    image: holepunch-node:local
    build:
      context: ..
      dockerfile: apps/holepunch-node/Dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 6
  
volumes:
  pgdata:
  pgadmin:

networks:
  default:
    name: holepunch-node
