version: '3'

dotenv: ['.env']
silent: true

tasks:
  boot:
    cmds:
      - docker-compose up -d --build

  reboot:
    cmds:
      - task down
      - task boot

  up:
    cmds:
      - docker-compose up -d --build

  down:
    cmds:
      - docker-compose down -v --remove-orphans